apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer
  name: consumer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - image: 968225077300.dkr.ecr.us-west-1.amazonaws.com/devops-na-nuvem/strimzi/consumer:v2.0
        name: consumer
